
export const CREATE_QUOTE = 'CREATE_QUOTE';
export const FETCH_QUOTES = 'FETCH_QUOTES';
export const FETCH_QUOTE = 'FETCH_QUOTE';
export const DELETE_STREAM = 'DELETE_STREAM';
export const FETCH_FIREBASE = 'FETCH_FIREBASE';